# Generated by Django 6.0 on 2026-02-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='benefits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='whatToExpect',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='certifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
