# Generated by Django 6.0 on 2025-12-31 03:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classbooking_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='FitnessClass'),
        ),
    ]
