# Generated by Django 6.0 on 2025-12-31 03:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_feedback_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymgallery',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='GymGallery'),
        ),
        migrations.AlterField(
            model_name='gymservice',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='GymService'),
        ),
    ]
