# Generated by Django 6.0 on 2026-01-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_gymgallery_image_alter_gymservice_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
