# Generated by Django 6.0 on 2026-02-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('lose-weight', 'Lose Weight'), ('build-muscle', 'Build Muscle'), ('improve-fitness', 'Improve Fitness'), ('flexibility', 'Flexibility')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
