# Generated by Django 6.0 on 2026-02-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_of_birth_user_emergency_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTrialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('fitness_goal', models.CharField(choices=[('lose-weight', 'Lose Weight'), ('build-muscle', 'Build Muscle'), ('improve-fitness', 'Improve Fitness'), ('flexibility', 'Flexibility'), ('competitive', 'Competition Prep')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False)),
            ],
        ),
    ]
