# Generated by Django 6.0 on 2025-12-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='name',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly')], max_length=50),
        ),
    ]
