# Generated by Django 6.0 on 2026-02-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
