# Generated by Django 6.0 on 2025-12-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membershipplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
